name = "porto-page"
compatibility_date = "2026-07-23"
[[kv_namespaces]]
binding = "SESSION"
id = "47501062e6084e04a3a784159c8df487"

[assets]
directory = "./dist/client"
binding = "ASSETS"

[vars]
GITHUB_USERNAME = "AzizPrayoga1"
CTFTIME_TEAM_ID = "426938"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "c2e5918d-adaf-437b-9040-8e8e848fb9ee"
migrations_dir = "drizzle/migrations"

[triggers]
crons = [
  "0 0 1 * *",  # Monthly (GitHub)
  "0 0 * * 1"   # Weekly (CTFtime)
]